name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Escrevendo usando docker
        run: docker run docker/whalesay cowsay GUILHERME NUNES

      - name: Escrevendo multiplas linhas
        run: |
          echo Ola Mundo
          echo Hello World
          echo Hola mundo
          echo Bonjour le monde
